# A list of amenities to display to a user
amenity = [
    {'label': 'TV', 'value': 'TV'},
    {'label': 'Cable TV', 'value': 'Cable TV'},
    {'label': 'Kitchen', 'value': 'Kitchen'},
    {'label': 'Free parking on premises ', 'value': 'Free parking on premises'},
    {'label': 'Breakfast ', 'value': 'Breakfast'},
    {'label': 'Elevator in building ', 'value': 'Elevator in building'},
    {'label': 'Heating ', 'value': 'Heating'},
    {'label': 'Washer ', 'value': 'Washer'},
    {'label': 'Dryer ', 'value': 'Dryer'},
    {'label': 'Smoke detector ', 'value': 'Smoke detector'},
    {'label': 'First aid kit ', 'value': 'First aid kit'},
    {'label': 'Safety card ', 'value': 'Safety card'},
    {'label': 'Fire extinguisher ', 'value': 'Fire extinguisher'},
    {'label': 'Hair dryer ', 'value': 'Hair dryer'},
    {'label': 'Laptop friendly workspace ', 'value': 'Laptop friendly workspace'},
    {'label': 'Wireless Internet ', 'value': 'Wireless Internet'},
    {'label': 'Air conditioning ', 'value': 'Air conditioning'},
    {'label': 'Gym ', 'value': 'Gym'},
    {'label': 'Carbon monoxide detector ', 'value': 'Carbon monoxide detector'},
    {'label': 'First aid kit ', 'value': 'First aid kit'},
    {'label': 'Wheelchair accessible ', 'value': 'Wheelchair accessible'},
    {'label': 'Family/kid friendly ', 'value': 'Family/kid friendly'},
    {'label': 'Lock on bedroom door ', 'value': 'Lock on bedroom door'},
    {'label': 'Hangers ', 'value': 'Hangers'},
    {'label': 'Iron ', 'value': 'Iron'},
    {'label': 'Pets allowed ', 'value': 'Pets allowed'},
    {'label': 'Breakfast ', 'value': 'Breakfast'},
    {'label': 'Suitable for events ', 'value': 'Suitable for events'},
    {'label': 'Shampoo ', 'value': 'Shampoo'},
    {'label': 'Private entrance ', 'value': 'Private entrance'},
    {'label': 'Smoking allowed ', 'value': 'Smoking allowed'},
    {'label': 'Hot tub ', 'value': 'Hot tub'},
    {'label': 'Pool ', 'value': 'Pool'},
    {'label': 'Babysitter recommendations ', 'value': 'Babysitter recommendations'},
    {'label': '24-hour check-in ', 'value': '24-hour check-in'},
    {'label': 'Buzzer/wireless intercom ', 'value': 'Buzzer/wireless intercom'},
    {'label': 'Self Check-In ', 'value': 'Self Check-In'},
    {'label': 'Lockbox ', 'value': 'Lockbox'},
    {'label': 'Cat(s) ', 'value': 'Cat(s)'},
]