''' 
Used for creating all dropdown values for the 
neighborhood dropdown in prediction.py
'''
neighborhoods = [
    {'label': 'Williamsburg', 'value': 'Williamsburg'},
    {'label': 'Bedford-Stuyvesant', 'value': 'Bedford-Stuyvesant'},
    {'label': 'Bushwick', 'value': 'Bushwick'},
    {'label': 'Mid-Wilshire', 'value': 'Mid-Wilshire'},
    {'label': 'Upper West Side', 'value': 'Upper West Side'},
    {'label': 'Harlem', 'value': 'Harlem'},
    {'label': 'Hollywood', 'value': 'Hollywood'},
    {'label': 'Hell\'s Kitchen', 'value': 'Hell\'s Kitchen'},
    {'label': 'Venice', 'value': 'Venice'},
    {'label': 'Upper East Side', 'value': 'Upper East Side'},
    {'label': 'Crown Heights', 'value': 'Crown Heights'},
    {'label': 'Astoria', 'value': 'Astoria'},
    {'label': 'Lower East Side', 'value': 'Lower East Side'},
    {'label': 'East Village', 'value': 'East Village'},
    {'label': 'East Harlem', 'value': 'East Harlem'},
    {'label': 'Mission District', 'value': 'Mission District'},
    {'label': 'West Hollywood', 'value': 'West Hollywood'},
    {'label': 'Greenpoint', 'value': 'Greenpoint'},
    {'label': 'Washington Heights', 'value': 'Washington Heights'},
    {'label': 'Chelsea', 'value': 'Chelsea'},
    {'label': 'Hamilton Heights', 'value': 'Hamilton Heights'},
    {'label': 'Alphabet City', 'value': 'Alphabet City'},
    {'label': 'Clinton Hill', 'value': 'Clinton Hill'},
    {'label': 'West Village', 'value': 'West Village'},
    {'label': 'Park Slope', 'value': 'Park Slope'},
    {'label': 'Long Beach', 'value': 'Long Beach'},
    {'label': 'Santa Monica', 'value': 'Santa Monica'},
    {'label': 'Downtown', 'value': 'Downtown'},
    {'label': 'Flatbush', 'value': 'Flatbush'},
    {'label': 'Capitol Hill', 'value': 'Capitol Hill'},
    {'label': 'Chinatown', 'value': 'Chinatown'},
    {'label': 'Hollywood Hills', 'value': 'Hollywood Hills'},
    {'label': 'Silver Lake', 'value': 'Silver Lake'},
    {'label': 'Midtown East', 'value': 'Midtown East'},
    {'label': 'Allston-Brighton', 'value': 'Allston-Brighton'},
    {'label': 'Echo Park', 'value': 'Echo Park'},
    {'label': 'Richmond District', 'value': 'Richmond District'},
    {'label': 'Western Addition/NOPA', 'value': 'Western Addition/NOPA'},
    {'label': 'SoMa', 'value': 'SoMa'},
    {'label': 'Financial District', 'value': 'Financial District'},
    {'label': 'Pasadena', 'value': 'Pasadena'},
    {'label': 'Bernal Heights', 'value': 'Bernal Heights'},
    {'label': 'Kips Bay', 'value': 'Kips Bay'},
    {'label': 'Lefferts Garden', 'value': 'Lefferts Garden'},
    {'label': 'Midtown', 'value': 'Midtown'},
    {'label': 'Noe Valley', 'value': 'Noe Valley'},
    {'label': 'North Hollywood', 'value': 'North Hollywood'},
    {'label': 'Mar Vista', 'value': 'Mar Vista'},
    {'label': 'Jamaica Plain', 'value': 'Jamaica Plain'},
    {'label': 'Columbia Heights', 'value': 'Columbia Heights'},
    {'label': 'Sunnyside', 'value': 'Sunnyside'},
    {'label': 'Back Bay', 'value': 'Back Bay'},
    {'label': 'Greenwich Village', 'value': 'Greenwich Village'},
    {'label': 'Dorchester', 'value': 'Dorchester'},
    {'label': 'Jamaica', 'value': 'Jamaica'},
    {'label': 'Westlake', 'value': 'Westlake'},
    {'label': 'Near Northeast/H Street Corridor', 'value': 'Near Northeast/H Street Corridor'},
    {'label': 'West Los Angeles', 'value': 'West Los Angeles'},
    {'label': 'Fort Greene', 'value': 'Fort Greene'},
    {'label': 'Westwood', 'value': 'Westwood'},
    {'label': 'Prospect Heights', 'value': 'Prospect Heights'},
    {'label': 'Lakeview', 'value': 'Lakeview'},
    {'label': 'Ridgewood', 'value': 'Ridgewood'},
    {'label': 'The Castro', 'value': 'The Castro'},
    {'label': 'Fenway/Kenmore', 'value': 'Fenway/Kenmore'},
    {'label': 'South LA', 'value': 'South LA'},
    {'label': 'Morningside Heights', 'value': 'Morningside Heights'},
    {'label': 'Sherman Oaks', 'value': 'Sherman Oaks'},
    {'label': 'South End', 'value': 'South End'},
    {'label': 'South Boston', 'value': 'South Boston'},
    {'label': 'Outer Sunset', 'value': 'Outer Sunset'},
    {'label': 'Logan Circle', 'value': 'Logan Circle'},
    {'label': 'U Street Corridor', 'value': 'U Street Corridor'},
    {'label': 'Dupont Circle', 'value': 'Dupont Circle'},
    {'label': 'Nob Hill', 'value': 'Nob Hill'},
    {'label': 'Mid-City', 'value': 'Mid-City'},
    {'label': 'Marina Del Rey', 'value': 'Marina Del Rey'},
    {'label': 'South Robertson', 'value': 'South Robertson'},
    {'label': 'Del Rey', 'value': 'Del Rey'},
    {'label': 'Soho', 'value': 'Soho'},
    {'label': 'Westchester/Playa Del Rey', 'value': 'Westchester/Playa Del Rey'},
    {'label': 'Logan Square', 'value': 'Logan Square'},
    {'label': 'Beverly Hills', 'value': 'Beverly Hills'},
    {'label': 'Adams Morgan', 'value': 'Adams Morgan'},
    {'label': 'Flushing', 'value': 'Flushing'},
    {'label': 'Glendale', 'value': 'Glendale'},
    {'label': 'Gramercy Park', 'value': 'Gramercy Park'},
    {'label': 'Pacific Heights', 'value': 'Pacific Heights'},
    {'label': 'Beacon Hill', 'value': 'Beacon Hill'},
    {'label': 'Los Feliz', 'value': 'Los Feliz'},
    {'label': 'Nolita', 'value': 'Nolita'},
    {'label': 'Studio City', 'value': 'Studio City'},
    {'label': 'Murray Hill', 'value': 'Murray Hill'},
    {'label': 'Malibu', 'value': 'Malibu'},
    {'label': 'Roxbury', 'value': 'Roxbury'},
    {'label': 'East Flatbush', 'value': 'East Flatbush'},
    {'label': 'East Boston', 'value': 'East Boston'},
    {'label': 'Redondo Beach', 'value': 'Redondo Beach'},
    {'label': 'East Hollywood', 'value': 'East Hollywood'},
    {'label': 'Burbank', 'value': 'Burbank'},
    {'label': 'Carroll Gardens', 'value': 'Carroll Gardens'},
    {'label': 'Potrero Hill', 'value': 'Potrero Hill'},
    {'label': 'Boerum Hill', 'value': 'Boerum Hill'},
    {'label': 'Flatiron District', 'value': 'Flatiron District'},
    {'label': 'Woodland Hills/Warner Center', 'value': 'Woodland Hills/Warner Center'},
    {'label': 'East New York', 'value': 'East New York'},
    {'label': 'Brentwood', 'value': 'Brentwood'},
    {'label': 'Shaw', 'value': 'Shaw'},
    {'label': 'Highland Park', 'value': 'Highland Park'},
    {'label': 'Westside', 'value': 'Westside'},
    {'label': 'Lincoln Park', 'value': 'Lincoln Park'},
    {'label': 'North End', 'value': 'North End'},
    {'label': 'Culver City', 'value': 'Culver City'},
    {'label': 'Loop', 'value': 'Loop'},
    {'label': 'Sunset Park', 'value': 'Sunset Park'},
    {'label': 'Haight-Ashbury', 'value': 'Haight-Ashbury'},
    {'label': 'Jackson Heights', 'value': 'Jackson Heights'},
    {'label': 'Wicker Park', 'value': 'Wicker Park'},
    {'label': 'Topanga', 'value': 'Topanga'},
    {'label': 'Laurel Canyon', 'value': 'Laurel Canyon'},
    {'label': 'Bloomingdale', 'value': 'Bloomingdale'},
    {'label': 'West End', 'value': 'West End'},
    {'label': 'West Town/Noble Square', 'value': 'West Town/Noble Square'},
    {'label': 'Forest Hills', 'value': 'Forest Hills'},
    {'label': 'Bel Air/Beverly Crest', 'value': 'Bel Air/Beverly Crest'},
    {'label': 'Pacific Palisades', 'value': 'Pacific Palisades'},
    {'label': 'Long Island City', 'value': 'Long Island City'},
    {'label': 'Marina', 'value': 'Marina'},
    {'label': 'Elmhurst', 'value': 'Elmhurst'},
    {'label': 'Mount Pleasant', 'value': 'Mount Pleasant'},
    {'label': 'Manhattan Beach', 'value': 'Manhattan Beach'},
    {'label': 'Palms', 'value': 'Palms'},
    {'label': 'Petworth', 'value': 'Petworth'},
    {'label': 'Kensington', 'value': 'Kensington'},
    {'label': 'Lower Haight', 'value': 'Lower Haight'},
    {'label': 'West Adams', 'value': 'West Adams'},
    {'label': 'Times Square/Theatre District', 'value': 'Times Square/Theatre District'},
    {'label': 'Inner Sunset', 'value': 'Inner Sunset'},
    {'label': 'Ditmars / Steinway', 'value': 'Ditmars / Steinway'},
    {'label': 'The Rockaways', 'value': 'The Rockaways'},
    {'label': 'Charlestown', 'value': 'Charlestown'},
    {'label': 'Windsor Terrace', 'value': 'Windsor Terrace'},
    {'label': 'Bayview', 'value': 'Bayview'},
    {'label': 'Eckington', 'value': 'Eckington'},
    {'label': 'Humboldt Park', 'value': 'Humboldt Park'},
    {'label': 'Georgetown', 'value': 'Georgetown'},
    {'label': 'South Beach', 'value': 'South Beach'},
    {'label': 'Downtown/Penn Quarter', 'value': 'Downtown/Penn Quarter'},
    {'label': 'Gowanus', 'value': 'Gowanus'},
    {'label': 'Uptown', 'value': 'Uptown'},
    {'label': 'Greenwood Heights', 'value': 'Greenwood Heights'},
    {'label': 'Brooklyn Heights', 'value': 'Brooklyn Heights'},
    {'label': 'Bay Ridge', 'value': 'Bay Ridge'},
    {'label': 'Duboce Triangle', 'value': 'Duboce Triangle'},
    {'label': 'Altadena', 'value': 'Altadena'},
    {'label': 'Russian Hill', 'value': 'Russian Hill'},
    {'label': 'Inwood', 'value': 'Inwood'},
    {'label': 'Mount Vernon Square', 'value': 'Mount Vernon Square'},
    {'label': 'Southwest Waterfront', 'value': 'Southwest Waterfront'},
    {'label': 'Tribeca', 'value': 'Tribeca'},
    {'label': 'Eagle Rock', 'value': 'Eagle Rock'},
    {'label': 'River North', 'value': 'River North'},
    {'label': 'Inglewood', 'value': 'Inglewood'},
    {'label': 'Downtown Brooklyn', 'value': 'Downtown Brooklyn'},
    {'label': 'Mount Washington', 'value': 'Mount Washington'},
    {'label': 'Alamo Square', 'value': 'Alamo Square'},
    {'label': 'Pilsen', 'value': 'Pilsen'},
    {'label': 'Union Square', 'value': 'Union Square'},
    {'label': 'Kingman Park', 'value': 'Kingman Park'},
    {'label': '16th Street Heights', 'value': '16th Street Heights'},
    {'label': 'Hayes Valley', 'value': 'Hayes Valley'},
    {'label': 'Rogers Park', 'value': 'Rogers Park'},
    {'label': 'Van Nuys', 'value': 'Van Nuys'},
    {'label': 'Mission Hill', 'value': 'Mission Hill'},
    {'label': 'Torrance', 'value': 'Torrance'},
    {'label': 'Excelsior', 'value': 'Excelsior'},
    {'label': 'Midwood', 'value': 'Midwood'},
    {'label': 'Woodside', 'value': 'Woodside'},
    {'label': 'Hyde Park', 'value': 'Hyde Park'},
    {'label': 'Encino', 'value': 'Encino'},
    {'label': 'Valley Village', 'value': 'Valley Village'},
    {'label': 'Ukrainian Village', 'value': 'Ukrainian Village'},
    {'label': 'Hermosa Beach', 'value': 'Hermosa Beach'},
    {'label': 'Telegraph Hill', 'value': 'Telegraph Hill'},
    {'label': 'Cole Valley', 'value': 'Cole Valley'},
    {'label': 'Cahuenga Pass', 'value': 'Cahuenga Pass'},
    {'label': 'Foggy Bottom', 'value': 'Foggy Bottom'},
    {'label': 'Alhambra', 'value': 'Alhambra'},
    {'label': 'Arcadia', 'value': 'Arcadia'},
    {'label': 'North Beach', 'value': 'North Beach'},
    {'label': 'Twin Peaks', 'value': 'Twin Peaks'},
    {'label': 'Sheepshead Bay', 'value': 'Sheepshead Bay'},
    {'label': 'Avondale', 'value': 'Avondale'},
    {'label': 'Roslindale', 'value': 'Roslindale'},
    {'label': 'Atwater Village', 'value': 'Atwater Village'},
    {'label': 'Old Town', 'value': 'Old Town'},
    {'label': 'Glen Park', 'value': 'Glen Park'},
    {'label': 'Valley Glen', 'value': 'Valley Glen'},
    {'label': 'Canarsie', 'value': 'Canarsie'},
    {'label': 'Kalorama', 'value': 'Kalorama'},
    {'label': 'Barney Circle', 'value': 'Barney Circle'},
    {'label': 'Cow Hollow', 'value': 'Cow Hollow'},
    {'label': 'Edgewater', 'value': 'Edgewater'},
    {'label': 'Trinidad', 'value': 'Trinidad'},
    {'label': 'Parkside', 'value': 'Parkside'},
    {'label': 'Bronzeville', 'value': 'Bronzeville'},
    {'label': 'Cleveland Park', 'value': 'Cleveland Park'},
    {'label': 'South Loop/Printers Row', 'value': 'South Loop/Printers Row'},
    {'label': 'Little Italy/UIC', 'value': 'Little Italy/UIC'},
    {'label': 'Richmond Hill', 'value': 'Richmond Hill'},
    {'label': 'Brookland', 'value': 'Brookland'},
    {'label': 'Glover Park', 'value': 'Glover Park'},
    {'label': 'Park View', 'value': 'Park View'},
    {'label': 'Roosevelt Island', 'value': 'Roosevelt Island'},
    {'label': 'Irving Park', 'value': 'Irving Park'},
    {'label': 'Corona', 'value': 'Corona'},
    {'label': 'El Segundo', 'value': 'El Segundo'},
    {'label': 'Monterey Park', 'value': 'Monterey Park'},
    {'label': 'Tarzana', 'value': 'Tarzana'},
    {'label': 'Judiciary Square', 'value': 'Judiciary Square'},
    {'label': 'Bucktown', 'value': 'Bucktown'},
    {'label': 'Rego Park', 'value': 'Rego Park'},
    {'label': 'Boyle Heights', 'value': 'Boyle Heights'},
    {'label': 'Mission Terrace', 'value': 'Mission Terrace'},
    {'label': 'Reseda', 'value': 'Reseda'},
    {'label': 'Downtown Crossing', 'value': 'Downtown Crossing'},
    {'label': 'Brooklyn Navy Yard', 'value': 'Brooklyn Navy Yard'},
    {'label': 'San Gabriel', 'value': 'San Gabriel'},
    {'label': 'LeDroit Park', 'value': 'LeDroit Park'},
    {'label': 'Lincoln Square', 'value': 'Lincoln Square'},
    {'label': 'Toluca Lake', 'value': 'Toluca Lake'},
    {'label': 'Gardena', 'value': 'Gardena'},
    {'label': 'Tenderloin', 'value': 'Tenderloin'},
    {'label': 'West Loop/Greektown', 'value': 'West Loop/Greektown'},
    {'label': 'Theater District', 'value': 'Theater District'},
    {'label': 'Noho', 'value': 'Noho'},
    {'label': 'Lincoln Heights', 'value': 'Lincoln Heights'},
    {'label': 'Hawthorne', 'value': 'Hawthorne'},
    {'label': 'Glassell Park', 'value': 'Glassell Park'},
    {'label': 'Civic Center', 'value': 'Civic Center'},
    {'label': 'San Pedro', 'value': 'San Pedro'},
    {'label': 'West Roxbury', 'value': 'West Roxbury'},
    {'label': 'Northridge', 'value': 'Northridge'},
    {'label': 'Temple City', 'value': 'Temple City'},
    {'label': 'Lake Balboa', 'value': 'Lake Balboa'},
    {'label': 'Cobble Hill', 'value': 'Cobble Hill'},
    {'label': 'Hudson Square', 'value': 'Hudson Square'},
    {'label': 'Truxton Circle', 'value': 'Truxton Circle'},
    {'label': 'Andersonville', 'value': 'Andersonville'},
    {'label': 'South Pasadena', 'value': 'South Pasadena'},
    {'label': 'Mott Haven', 'value': 'Mott Haven'},
    {'label': 'Edgewood', 'value': 'Edgewood'},
    {'label': 'Crocker Amazon', 'value': 'Crocker Amazon'},
    {'label': 'Wrigleyville', 'value': 'Wrigleyville'},
    {'label': 'Arts District', 'value': 'Arts District'},
    {'label': 'St. George', 'value': 'St. George'},
    {'label': 'Manor Park', 'value': 'Manor Park'},
    {'label': 'Bayside', 'value': 'Bayside'},
    {'label': 'Balboa Terrace', 'value': 'Balboa Terrace'},
    {'label': 'Streeterville', 'value': 'Streeterville'},
    {'label': 'West Hills', 'value': 'West Hills'},
    {'label': 'Ingleside', 'value': 'Ingleside'},
    {'label': 'Lakeshore', 'value': 'Lakeshore'},
    {'label': 'North Center', 'value': 'North Center'},
    {'label': 'Flatlands', 'value': 'Flatlands'},
    {'label': 'Baldwin Hills', 'value': 'Baldwin Hills'},
    {'label': 'Battery Park City', 'value': 'Battery Park City'},
    {'label': 'Bridgeport', 'value': 'Bridgeport'},
    {'label': 'Gravesend', 'value': 'Gravesend'},
    {'label': 'Visitacion Valley', 'value': 'Visitacion Valley'},
    {'label': 'West Ridge', 'value': 'West Ridge'},
    {'label': 'Bensonhurst', 'value': 'Bensonhurst'},
    {'label': 'West Covina', 'value': 'West Covina'},
    {'label': 'Woodley Park', 'value': 'Woodley Park'},
    {'label': 'Fisherman\'s Wharf', 'value': 'Fisherman\'s Wharf'},
    {'label': 'Navy Yard', 'value': 'Navy Yard'},
    {'label': 'Little Village', 'value': 'Little Village'},
    {'label': 'Red Hook', 'value': 'Red Hook'},
    {'label': 'Little Italy', 'value': 'Little Italy'},
    {'label': 'Concourse', 'value': 'Concourse'},
    {'label': 'El Sereno', 'value': 'El Sereno'},
    {'label': 'Gold Coast', 'value': 'Gold Coast'},
    {'label': 'Oceanview', 'value': 'Oceanview'},
    {'label': 'Meatpacking District', 'value': 'Meatpacking District'},
    {'label': 'Anacostia', 'value': 'Anacostia'},
    {'label': 'Near North Side', 'value': 'Near North Side'},
    {'label': 'Woodhaven', 'value': 'Woodhaven'},
    {'label': 'Rancho Palos Verdes', 'value': 'Rancho Palos Verdes'},
    {'label': 'Garfield Park', 'value': 'Garfield Park'},
    {'label': 'Maspeth', 'value': 'Maspeth'},
    {'label': 'Presidio Heights', 'value': 'Presidio Heights'},
    {'label': 'Brownsville', 'value': 'Brownsville'},
    {'label': 'DUMBO', 'value': 'DUMBO'},
    {'label': 'Roscoe Village', 'value': 'Roscoe Village'},
    {'label': 'Kew Garden Hills', 'value': 'Kew Garden Hills'},
    {'label': 'Chevy Chase', 'value': 'Chevy Chase'},
    {'label': 'Brighton Beach', 'value': 'Brighton Beach'},
    {'label': 'Takoma', 'value': 'Takoma'},
    {'label': 'Whittier', 'value': 'Whittier'},
    {'label': 'Ozone Park', 'value': 'Ozone Park'},
    {'label': 'Kenwood', 'value': 'Kenwood'},
    {'label': 'East Elmhurst', 'value': 'East Elmhurst'},
    {'label': 'Michigan Park', 'value': 'Michigan Park'},
    {'label': 'Woodlawn', 'value': 'Woodlawn'},
    {'label': 'Columbia Street Waterfront', 'value': 'Columbia Street Waterfront'},
    {'label': 'Winnetka', 'value': 'Winnetka'},
    {'label': 'Palisades', 'value': 'Palisades'},
    {'label': 'Skid Row', 'value': 'Skid Row'},
    {'label': 'Mattapan', 'value': 'Mattapan'},
    {'label': 'Baychester', 'value': 'Baychester'},
    {'label': 'Monrovia', 'value': 'Monrovia'},
    {'label': 'Canoga Park', 'value': 'Canoga Park'},
    {'label': 'Portage Park', 'value': 'Portage Park'},
    {'label': 'Boystown', 'value': 'Boystown'},
    {'label': 'Borough Park', 'value': 'Borough Park'},
    {'label': 'Pleasant Plains', 'value': 'Pleasant Plains'},
    {'label': 'Mission Bay', 'value': 'Mission Bay'},
    {'label': 'East Los Angeles', 'value': 'East Los Angeles'},
    {'label': 'Burleith', 'value': 'Burleith'},
    {'label': 'Soundview', 'value': 'Soundview'},
    {'label': 'Stapleton', 'value': 'Stapleton'},
    {'label': 'Riverdale', 'value': 'Riverdale'},
    {'label': 'Rosemead', 'value': 'Rosemead'},
    {'label': 'West Brighton', 'value': 'West Brighton'},
    {'label': 'Dogpatch', 'value': 'Dogpatch'},
    {'label': 'Lakewood', 'value': 'Lakewood'},
    {'label': 'Sunland/Tujunga', 'value': 'Sunland/Tujunga'},
    {'label': 'Middle Village', 'value': 'Middle Village'},
    {'label': 'Fairlawn', 'value': 'Fairlawn'},
    {'label': 'American University Park', 'value': 'American University Park'},
    {'label': 'Woodridge', 'value': 'Woodridge'},
    {'label': 'Granada Hills North', 'value': 'Granada Hills North'},
    {'label': 'Harbor Gateway', 'value': 'Harbor Gateway'},
    {'label': 'Albany Park', 'value': 'Albany Park'},
    {'label': 'Highbridge', 'value': 'Highbridge'},
    {'label': 'Lamond Riggs', 'value': 'Lamond Riggs'},
    {'label': 'Lawndale', 'value': 'Lawndale'},
    {'label': 'Carson', 'value': 'Carson'},
    {'label': 'Azusa', 'value': 'Azusa'},
    {'label': 'Elysian Valley', 'value': 'Elysian Valley'},
    {'label': 'El Monte', 'value': 'El Monte'},
    {'label': 'Carver Langston', 'value': 'Carver Langston'},
    {'label': 'Portola', 'value': 'Portola'},
    {'label': 'Bedford Park', 'value': 'Bedford Park'},
    {'label': 'Parkchester', 'value': 'Parkchester'},
    {'label': 'Concourse Village', 'value': 'Concourse Village'},
    {'label': 'Kingsbridge Heights', 'value': 'Kingsbridge Heights'},
    {'label': 'Tremont', 'value': 'Tremont'},
    {'label': 'Lomita', 'value': 'Lomita'},
    {'label': 'Wakefield', 'value': 'Wakefield'},
    {'label': 'Near West Side', 'value': 'Near West Side'},
    {'label': 'South Ozone Park', 'value': 'South Ozone Park'},
    {'label': 'South Shore', 'value': 'South Shore'},
    {'label': 'Bronxdale', 'value': 'Bronxdale'},
    {'label': 'River West', 'value': 'River West'},
    {'label': 'La Canada Flintridge', 'value': 'La Canada Flintridge'},
    {'label': 'Coney Island', 'value': 'Coney Island'},
    {'label': 'Diamond Heights', 'value': 'Diamond Heights'},
    {'label': 'Downey', 'value': 'Downey'},
    {'label': 'Dyker Heights', 'value': 'Dyker Heights'},
    {'label': 'Crestwood', 'value': 'Crestwood'},
    {'label': 'University Heights', 'value': 'University Heights'},
    {'label': 'Brooklyn', 'value': 'Brooklyn'},
    {'label': 'Glendora', 'value': 'Glendora'},
    {'label': 'Shepherd Park', 'value': 'Shepherd Park'},
    {'label': 'Park Versailles', 'value': 'Park Versailles'},
    {'label': 'Cathedral Heights', 'value': 'Cathedral Heights'},
    {'label': 'Oakland', 'value': 'Oakland'},
    {'label': 'Manhattan', 'value': 'Manhattan'},
    {'label': 'North Hills West', 'value': 'North Hills West'},
    {'label': 'Cerritos', 'value': 'Cerritos'},
    {'label': 'Brightwood', 'value': 'Brightwood'},
    {'label': 'Kingsbridge', 'value': 'Kingsbridge'},
    {'label': 'Sun Valley', 'value': 'Sun Valley'},
    {'label': 'Forest Hill', 'value': 'Forest Hill'},
    {'label': 'Englewood', 'value': 'Englewood'},
    {'label': 'Buena Vista', 'value': 'Buena Vista'},
    {'label': 'Hermon', 'value': 'Hermon'},
    {'label': 'Tompkinsville', 'value': 'Tompkinsville'},
    {'label': 'East San Gabriel', 'value': 'East San Gabriel'},
    {'label': 'Fordham', 'value': 'Fordham'},
    {'label': 'Jefferson Park', 'value': 'Jefferson Park'},
    {'label': 'Colonial Village', 'value': 'Colonial Village'},
    {'label': 'Claremont', 'value': 'Claremont'},
    {'label': 'Williamsbridge', 'value': 'Williamsbridge'},
    {'label': 'Langdon', 'value': 'Langdon'},
    {'label': 'Foxhall', 'value': 'Foxhall'},
    {'label': 'Montecito Heights', 'value': 'Montecito Heights'},
    {'label': 'South Street Seaport', 'value': 'South Street Seaport'},
    {'label': 'Panorama City', 'value': 'Panorama City'},
    {'label': 'Hillcrest', 'value': 'Hillcrest'},
    {'label': 'Cypress Park', 'value': 'Cypress Park'},
    {'label': 'Allerton', 'value': 'Allerton'},
    {'label': 'Eastchester', 'value': 'Eastchester'},
    {'label': 'Norwood', 'value': 'Norwood'},
    {'label': 'Fort Lincoln', 'value': 'Fort Lincoln'},
    {'label': 'Covina', 'value': 'Covina'},
    {'label': 'Chatsworth', 'value': 'Chatsworth'},
    {'label': 'Pico Rivera', 'value': 'Pico Rivera'},
    {'label': 'Back of the Yards', 'value': 'Back of the Yards'},
    {'label': 'La Mirada', 'value': 'La Mirada'},
    {'label': 'La Crescenta-Montrose', 'value': 'La Crescenta-Montrose'},
    {'label': 'West Portal', 'value': 'West Portal'},
    {'label': 'Belmont Cragin', 'value': 'Belmont Cragin'},
    {'label': 'Marshall Heights', 'value': 'Marshall Heights'},
    {'label': 'Benning Ridge', 'value': 'Benning Ridge'},
    {'label': 'Bellflower', 'value': 'Bellflower'},
    {'label': 'Pelham Bay', 'value': 'Pelham Bay'},
    {'label': 'City Island', 'value': 'City Island'},
    {'label': 'Crotona', 'value': 'Crotona'},
    {'label': 'North Lawndale', 'value': 'North Lawndale'},
    {'label': 'Port Morris', 'value': 'Port Morris'},
    {'label': 'North Michigan Park', 'value': 'North Michigan Park'},
    {'label': 'Twining', 'value': 'Twining'},
    {'label': 'Bath Beach', 'value': 'Bath Beach'},
    {'label': 'Leather District', 'value': 'Leather District'},
    {'label': 'Harbor City', 'value': 'Harbor City'},
    {'label': 'College Point', 'value': 'College Point'},
    {'label': 'Sylmar', 'value': 'Sylmar'},
    {'label': 'Kent', 'value': 'Kent'},
    {'label': 'Midland Beach', 'value': 'Midland Beach'},
    {'label': 'North Hills East', 'value': 'North Hills East'},
    {'label': 'Longwood', 'value': 'Longwood'},
    {'label': 'Morrisania', 'value': 'Morrisania'},
    {'label': 'Morris Heights', 'value': 'Morris Heights'},
    {'label': 'Hunts Point', 'value': 'Hunts Point'},
    {'label': 'Compton', 'value': 'Compton'},
    {'label': 'Friendship Heights', 'value': 'Friendship Heights'},
    {'label': 'River Terrace', 'value': 'River Terrace'},
    {'label': 'Pacoima', 'value': 'Pacoima'},
    {'label': 'Elm Park', 'value': 'Elm Park'},
    {'label': 'Wesley Heights', 'value': 'Wesley Heights'},
    {'label': 'Stronghold', 'value': 'Stronghold'},
    {'label': 'North Cleveland Park', 'value': 'North Cleveland Park'},
    {'label': 'Monterey Hills', 'value': 'Monterey Hills'},
    {'label': 'Central Northeast/Mahaning Heights', 'value': 'Central Northeast/Mahaning Heights'},
    {'label': 'Sea Gate', 'value': 'Sea Gate'},
    {'label': 'Throgs Neck', 'value': 'Throgs Neck'},
    {'label': 'Signal Hill', 'value': 'Signal Hill'},
    {'label': 'Chestnut Hill', 'value': 'Chestnut Hill'},
    {'label': 'San Marino', 'value': 'San Marino'},
    {'label': 'Utopia', 'value': 'Utopia'},
    {'label': 'Marble Hill', 'value': 'Marble Hill'},
    {'label': 'Japantown', 'value': 'Japantown'},
    {'label': 'Palos Verdes', 'value': 'Palos Verdes'},
    {'label': 'Porter Ranch', 'value': 'Porter Ranch'},
    {'label': 'The Bronx', 'value': 'The Bronx'},
    {'label': 'Whitestone', 'value': 'Whitestone'},
    {'label': 'Pleasant Hill', 'value': 'Pleasant Hill'},
    {'label': 'Vinegar Hill', 'value': 'Vinegar Hill'},
    {'label': 'Norwalk', 'value': 'Norwalk'},
    {'label': 'Benning', 'value': 'Benning'},
    {'label': 'Castle Hill ', 'value': 'Castle Hill '},
    {'label': 'Norwood Park', 'value': 'Norwood Park'},
    {'label': 'Mount Eden', 'value': 'Mount Eden'},
    {'label': 'Van Nest', 'value': 'Van Nest'},
    {'label': 'Deanwood', 'value': 'Deanwood'},
    {'label': 'Grand Crossing', 'value': 'Grand Crossing'},
    {'label': 'South Chicago', 'value': 'South Chicago'},
    {'label': 'Lynwood', 'value': 'Lynwood'},
    {'label': 'Dunning', 'value': 'Dunning'},
    {'label': 'Sierra Madre', 'value': 'Sierra Madre'},
    {'label': 'Duarte', 'value': 'Duarte'},
    {'label': 'Eltingville', 'value': 'Eltingville'},
    {'label': 'Montebello', 'value': 'Montebello'},
    {'label': 'Sea Cliff', 'value': 'Sea Cliff'},
    {'label': 'East Corner', 'value': 'East Corner'},
    {'label': 'Hawaiian Gardens', 'value': 'Hawaiian Gardens'},
    {'label': 'Benning Heights', 'value': 'Benning Heights'},
    {'label': 'Armour Square', 'value': 'Armour Square'},
    {'label': 'Morris Park', 'value': 'Morris Park'},
    {'label': 'Melrose', 'value': 'Melrose'},
    {'label': 'New Brighton', 'value': 'New Brighton'},
    {'label': 'Hermosa', 'value': 'Hermosa'},
    {'label': 'Eastland Gardens', 'value': 'Eastland Gardens'},
    {'label': 'South Whittier', 'value': 'South Whittier'},
    {'label': 'West Puente Valley', 'value': 'West Puente Valley'},
    {'label': 'Randle Highlands', 'value': 'Randle Highlands'},
    {'label': 'Ivy City', 'value': 'Ivy City'},
    {'label': 'Tottenville', 'value': 'Tottenville'},
    {'label': 'Westerleigh', 'value': 'Westerleigh'},
    {'label': 'Great Kills', 'value': 'Great Kills'},
    {'label': 'Congress Heights', 'value': 'Congress Heights'},
    {'label': 'Daly City', 'value': 'Daly City'},
    {'label': 'Howard Beach', 'value': 'Howard Beach'},
    {'label': 'Rosebank', 'value': 'Rosebank'},
    {'label': 'Edenwald', 'value': 'Edenwald'},
    {'label': 'Spuyten Duyvil', 'value': 'Spuyten Duyvil'},
    {'label': 'McKinley Park', 'value': 'McKinley Park'},
    {'label': 'Gallaudet', 'value': 'Gallaudet'},
    {'label': 'Westmont', 'value': 'Westmont'},
    {'label': 'Good Hope', 'value': 'Good Hope'},
    {'label': 'Bergen Beach', 'value': 'Bergen Beach'},
    {'label': 'Concord', 'value': 'Concord'},
    {'label': 'Washington Highlands', 'value': 'Washington Highlands'},
    {'label': 'Willowbrook', 'value': 'Willowbrook'},
    {'label': 'Lindenwood', 'value': 'Lindenwood'},
    {'label': 'Austin', 'value': 'Austin'},
    {'label': 'North Park', 'value': 'North Park'},
    {'label': 'Bradbury', 'value': 'Bradbury'},
    {'label': 'Douglass', 'value': 'Douglass'},
    {'label': 'Belmont', 'value': 'Belmont'},
    {'label': 'Fort Dupont', 'value': 'Fort Dupont'},
    {'label': 'Washington Park', 'value': 'Washington Park'},
    {'label': 'South San Gabriel', 'value': 'South San Gabriel'},
    {'label': 'West Farms', 'value': 'West Farms'},
    {'label': 'Grasmere', 'value': 'Grasmere'},
    {'label': 'West Lawn', 'value': 'West Lawn'},
    {'label': 'Meiers Corners', 'value': 'Meiers Corners'},
    {'label': 'Naylor Gardens', 'value': 'Naylor Gardens'},
    {'label': 'Morgan Park', 'value': 'Morgan Park'},
    {'label': 'Randall Manor', 'value': 'Randall Manor'},
    {'label': 'St. Elizabeths', 'value': 'St. Elizabeths'},
    {'label': 'Mt Rainier/Brentwood, MD', 'value': 'Mt Rainier/Brentwood, MD'},
    {'label': 'Shipley Terrace', 'value': 'Shipley Terrace'},
    {'label': 'Beverly', 'value': 'Beverly'},
    {'label': 'Fort Davis', 'value': 'Fort Davis'},
    {'label': 'Winthrop', 'value': 'Winthrop'},
    {'label': 'Marine Park', 'value': 'Marine Park'},
    {'label': 'Grymes Hill', 'value': 'Grymes Hill'},
    {'label': 'Baldwin Park', 'value': 'Baldwin Park'},
    {'label': 'La Puente', 'value': 'La Puente'},
    {'label': 'Dupont Park', 'value': 'Dupont Park'},
    {'label': 'Huntington Park', 'value': 'Huntington Park'},
    {'label': 'Bellevue', 'value': 'Bellevue'},
    {'label': 'Watts', 'value': 'Watts'},
    {'label': 'Chatham', 'value': 'Chatham'},
    {'label': 'Fresh Meadows', 'value': 'Fresh Meadows'},
    {'label': 'Greenway', 'value': 'Greenway'},
    {'label': 'Silver Spring, MD', 'value': 'Silver Spring, MD'},
    {'label': 'Port Richmond', 'value': 'Port Richmond'},
    {'label': 'Queens', 'value': 'Queens'},
    {'label': 'South Gate', 'value': 'South Gate'},
    {'label': 'Somerville', 'value': 'Somerville'},
    {'label': 'West Elsdon', 'value': 'West Elsdon'},
    {'label': 'Fort Totten', 'value': 'Fort Totten'},
    {'label': 'Berkley', 'value': 'Berkley'},
    {'label': 'Garfield Ridge', 'value': 'Garfield Ridge'},
    {'label': 'Arleta', 'value': 'Arleta'},
    {'label': 'O\'Hare', 'value': 'O\'Hare'},
    {'label': 'Takoma Park, MD', 'value': 'Takoma Park, MD'},
    {'label': 'Fort Wadsworth', 'value': 'Fort Wadsworth'},
    {'label': 'Castleton Corners', 'value': 'Castleton Corners'},
    {'label': 'Hillbrook', 'value': 'Hillbrook'},
    {'label': 'Gateway', 'value': 'Gateway'},
    {'label': 'Government Center', 'value': 'Government Center'},
    {'label': 'Florence-Graham', 'value': 'Florence-Graham'},
    {'label': 'Mariners Harbor', 'value': 'Mariners Harbor'},
    {'label': 'Brookline', 'value': 'Brookline'},
    {'label': 'Spring Valley', 'value': 'Spring Valley'},
    {'label': 'Paramount', 'value': 'Paramount'},
    {'label': 'Alondra Park', 'value': 'Alondra Park'},
    {'label': 'Westchester Village', 'value': 'Westchester Village'},
    {'label': 'Presidio', 'value': 'Presidio'},
    {'label': 'New Springville', 'value': 'New Springville'},
    {'label': 'Galewood', 'value': 'Galewood'},
    {'label': 'Bell', 'value': 'Bell'},
    {'label': 'Emerson Hill', 'value': 'Emerson Hill'},
    {'label': 'Cambridge', 'value': 'Cambridge'},
    {'label': 'Rolling Hills Estates', 'value': 'Rolling Hills Estates'},
    {'label': 'Skyland', 'value': 'Skyland'},
    {'label': 'Santa Fe Springs', 'value': 'Santa Fe Springs'},
    {'label': 'West Athens', 'value': 'West Athens'},
    {'label': 'Archer Heights', 'value': 'Archer Heights'},
    {'label': 'Huguenot', 'value': 'Huguenot'},
    {'label': 'Auburn Gresham', 'value': 'Auburn Gresham'},
    {'label': 'Co-op City', 'value': 'Co-op City'},
    {'label': 'South El Monte', 'value': 'South El Monte'},
    {'label': 'Roseland', 'value': 'Roseland'},
    {'label': 'Brighton Park', 'value': 'Brighton Park'},
    {'label': 'Mission Hills', 'value': 'Mission Hills'},
    {'label': 'Clearing', 'value': 'Clearing'},
    {'label': 'Woodland', 'value': 'Woodland'},
    {'label': 'Printers Row', 'value': 'Printers Row'},
    {'label': 'Mill Basin', 'value': 'Mill Basin'},
    {'label': 'Wilmington', 'value': 'Wilmington'},
    {'label': 'Oakwood', 'value': 'Oakwood'},
    {'label': 'Observatory Circle', 'value': 'Observatory Circle'},
    {'label': 'Bethesda, MD', 'value': 'Bethesda, MD'},
    {'label': 'Commerce', 'value': 'Commerce'},
    {'label': 'West Town', 'value': 'West Town'},
    {'label': 'Hilcrest Heights/Marlow Heights, MD', 'value': 'Hilcrest Heights/Marlow Heights, MD'},
    {'label': 'Lighthouse HIll', 'value': 'Lighthouse HIll'},
    {'label': 'Irwindale', 'value': 'Irwindale'},
    {'label': 'Harvard Square', 'value': 'Harvard Square'},
    {'label': 'Chillum, MD', 'value': 'Chillum, MD'},
    {'label': 'Watertown', 'value': 'Watertown'},
    {'label': 'Montclare', 'value': 'Montclare'},
    {'label': 'Graniteville', 'value': 'Graniteville'},
    {'label': 'Clifton', 'value': 'Clifton'},
    {'label': 'Pullman', 'value': 'Pullman'},
    {'label': 'Mt. Pleasant', 'value': 'Mt. Pleasant'},
    {'label': 'Rossville', 'value': 'Rossville'},
    {'label': 'Rolling Hills', 'value': 'Rolling Hills'},
    {'label': 'Mt. Vernon Square', 'value': 'Mt. Vernon Square'},
    {'label': 'Magnificent Mile', 'value': 'Magnificent Mile'},
    {'label': 'Grant City', 'value': 'Grant City'},
    {'label': 'Barry Farm', 'value': 'Barry Farm'},
    {'label': 'Vernon', 'value': 'Vernon'},
    {'label': 'New Dorp Beach', 'value': 'New Dorp Beach'},
    {'label': 'La Habra', 'value': 'La Habra'},
    {'label': 'Coolidge Corner', 'value': 'Coolidge Corner'},
    {'label': 'Dongan Hills', 'value': 'Dongan Hills'},
    {'label': 'Massachusetts Heights', 'value': 'Massachusetts Heights'},
    {'label': 'Gerritsen Beach', 'value': 'Gerritsen Beach'},
    {'label': 'Annadale', 'value': 'Annadale'},
    {'label': 'Newton', 'value': 'Newton'},
    {'label': 'Todt Hill', 'value': 'Todt Hill'},
    {'label': 'Edison Park', 'value': 'Edison Park'},
    {'label': 'Ashburn', 'value': 'Ashburn'},
    {'label': 'Artesia', 'value': 'Artesia'},
    {'label': 'Country Club', 'value': 'Country Club'},
    {'label': 'Arboretum', 'value': 'Arboretum'},
    {'label': 'Near Northeast', 'value': 'Near Northeast'},
    {'label': 'Chevy Chase, MD', 'value': 'Chevy Chase, MD'},
    {'label': 'Old Soldiers\' Home', 'value': 'Old Soldiers\' Home'},
    {'label': 'Suitland-Silver Hill, MD', 'value': 'Suitland-Silver Hill, MD'},
    {'label': 'Garfield Heights', 'value': 'Garfield Heights'},
]